namespace TeamCord.Plugin.Natives
{
    public enum ServerInstancePropertiesRare
    {
        SERVERINSTANCE_DATABASE_VERSION = 0,
        SERVERINSTANCE_FILETRANSFER_PORT,
        SERVERINSTANCE_SERVER_ENTROPY,
        SERVERINSTANCE_MONTHLY_TIMESTAMP,
        SERVERINSTANCE_MAX_DOWNLOAD_TOTAL_BANDWIDTH,
        SERVERINSTANCE_MAX_UPLOAD_TOTAL_BANDWIDTH,
        SERVERINSTANCE_GUEST_SERVERQUERY_GROUP,
        SERVERINSTANCE_SERVERQUERY_FLOOD_COMMANDS,       //how many commands we can issue while in the SERVERINSTANCE_SERVERQUERY_FLOOD_TIME window
        SERVERINSTANCE_SERVERQUERY_FLOOD_TIME,           //time window in seconds for max command execution check
        SERVERINSTANCE_SERVERQUERY_BAN_TIME,             //how many seconds someone get banned if he floods
        SERVERINSTANCE_TEMPLATE_SERVERADMIN_GROUP,
        SERVERINSTANCE_TEMPLATE_SERVERDEFAULT_GROUP,
        SERVERINSTANCE_TEMPLATE_CHANNELADMIN_GROUP,
        SERVERINSTANCE_TEMPLATE_CHANNELDEFAULT_GROUP,
        SERVERINSTANCE_PERMISSIONS_VERSION,
        SERVERINSTANCE_PENDING_CONNECTIONS_PER_IP,
        SERVERINSTANCE_SERVERQUERY_MAX_CONNECTIONS_PER_IP,
        SERVERINSTANCE_ENDMARKER_RARE,
    }
}