name: Release_package

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-version: '5.x'
      
    - name: Restore Packages
      run: nuget restore src\TeamCord.sln

    - name: Build Solution
      run: |
        msbuild.exe src\TeamCord.sln /t:TeamCord_Setup /p:platform="x64" /p:configuration="Release" /p:PostBuildEvent=
    
    - name: Rename setup files
      run: | 
        cd src\\TeamCord.Setup\\bin\\x64\\Release
        mv TeamCord.msi TeamCord-win-x64-${{github.ref_name}}.msi

    - name: Upload setup artifact
      uses: actions/upload-artifact@v3
      with:
        name: TeamCord-win-x64-${{github.ref_name}}.msi
        path: "src\\TeamCord.Setup\\bin\\x64\\Release\\TeamCord-win-x64-${{github.ref_name}}.msi"
        if-no-files-found: error
        retention-days: 7
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: TeamCord-win-x64-${{github.ref_name}}.msi

    - name: Release files
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.md
        fail_on_unmatched_files: true
        files: |
          TeamCord-win-x64-${{github.ref_name}}.msi
        